import type { Metadata } from "next";
import "./globals.css";
import ClerkClientProvider from "./components/ClerkClientProvider";

export const metadata: Metadata = {
  title: "vinext on Cloudflare Workers",
  description: "Generated by create-vinext-app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <ClerkClientProvider>{children}</ClerkClientProvider>
      </body>
    </html>
  );
}
